DEFAULT_ATTACK_DAMAGE = 2

HVZ_BASE_FILE_PATH = "hvz/data/hvz/functions/"
KIT_FILE_PATH = f"{HVZ_BASE_FILE_PATH}kit/"
KIT_FILE_PATH_OLD = f"{HVZ_BASE_FILE_PATH}kit_old/"
CONTROL_FILE_PATH = f"{HVZ_BASE_FILE_PATH}control/"
HUMAN_KIT_PATH = f"{KIT_FILE_PATH}human_kits/"

ZOMBIE_SATURATION_TIMER_SCOREBOARD = "ZombieSatTimer"
ZOMBIE_SATURATION_TIMER_PLAYER = "zombieSatTimer"
ZOMBIE_SATURATION_TICKS_BETWEEN = 120

ZOMBIE_TEAM_NAME = "HVZZombie"
HUMAN_TEAM_NAME = "HVZHuman"

HUMAN_KIT_CSV_FILE_KIT_NAME = "KitName"
HUMAN_KIT_CSV_FILE_CHESTPLATE = "Chestplate"
HUMAN_KIT_CSV_FILE_ITEM_ONE = "Item1"
HUMAN_KIT_CSV_FILE_ITEM_TWO = "Item2"
HUMAN_KIT_CSV_FILE_ITEM_THREE = "Item3"
HUMAN_KIT_CSV_FILE_ITEM_FOUR = "Item4"

EXECUTE_AS_TARGET_COMMAND = "execute as @s run"
