DEFAULT_ATTACK_DAMAGE = 2

HVZ_BASE_FILE_PATH = "hvz/data/hvz/functions/"
KIT_FILE_PATH = f"{HVZ_BASE_FILE_PATH}kit/"
CONTROL_FILE_PATH = f"{HVZ_BASE_FILE_PATH}control/"

ZOMBIE_SATURATION_TIMER_SCOREBOARD = "ZombieSatTimer"
ZOMBIE_SATURATION_TIMER_PLAYER = "zombieSatTimer"
ZOMBIE_SATURATION_TICKS_BETWEEN = 120

ZOMBIE_TEAM_NAME = "HVZZombie"
HUMAN_TEAM_NAME = "HVZHuman"
