DEFAULT_ATTACK_DAMAGE = 2

HVZ_BASE_FILE_PATH = "hvz/data/hvz/functions/"
KIT_FILE_PATH = f"{HVZ_BASE_FILE_PATH}kit/"
KIT_FILE_PATH_OLD = f"{HVZ_BASE_FILE_PATH}kit_old/"
CONTROL_FILE_PATH = f"{HVZ_BASE_FILE_PATH}control/"
HUMAN_KIT_PATH = f"{KIT_FILE_PATH}human_kits/"
ZOMBIE_KIT_PATH = f"{KIT_FILE_PATH}zombie_kits/"

HVZ_CALL_FUNCTION_PATH = "hvz:"
HVZ_CALL_FUNCTION_KIT_PATH = f"{HVZ_CALL_FUNCTION_PATH}kit/"
HVZ_CALL_FUNCTION_HUMAN_KIT_PATH = f"{HVZ_CALL_FUNCTION_KIT_PATH}human_kits/"
HVZ_CALL_FUNCTION_ZOMBIE_KIT_PATH = f"{HVZ_CALL_FUNCTION_KIT_PATH}zombie_kits/"

ZOMBIE_SATURATION_TIMER_SCOREBOARD = "ZombieSatTimer"
ZOMBIE_SATURATION_TIMER_PLAYER = "zombieSatTimer"
ZOMBIE_SATURATION_TICKS_BETWEEN = 120

ZOMBIE_TEAM_NAME = "HVZZombie"
HUMAN_TEAM_NAME = "HVZHuman"

HUMAN_KIT_CSV_FILE_KIT_NAME = "KitName"
HUMAN_KIT_CSV_FILE_CHESTPLATE = "Chestplate"
HUMAN_KIT_CSV_FILE_ITEM_ONE = "Item1"
HUMAN_KIT_CSV_FILE_ITEM_TWO = "Item2"
HUMAN_KIT_CSV_FILE_ITEM_THREE = "Item3"
HUMAN_KIT_CSV_FILE_ITEM_FOUR = "Item4"

ZOMBIE_KIT_CSV_FILE_KIT_NAME = "KitName"
ZOMBIE_KIT_CSV_FILE_KILLS_NEEDED = "KillsNeeded"
ZOMBIE_KIT_CSV_FILE_CHESTPLATE = "Chestplate"
ZOMBIE_KIT_CSV_FILE_BOOTS = "Boots"
ZOMBIE_KIT_CSV_FILE_PANTS = "Pants"
ZOMBIE_KIT_CSV_FILE_HELMET = "ZombieHead"
ZOMBIE_KIT_CSV_FILE_ITEM_ONE = "Item1"
ZOMBIE_KIT_CSV_FILE_ITEM_TWO = "Item2"
ZOMBIE_KIT_CSV_FILE_ITEM_THREE = "Item3"
ZOMBIE_KIT_CSV_FILE_ITEM_FOUR = "Item4"
ZOMBIE_KIT_CSV_FILE_ITEM_FIVE = "Item5"
ZOMBIE_KIT_CSV_FILE_ITEM_SIX = "Item6"

EXECUTE_AS_TARGET_COMMAND = "execute as @s run"
EXECUTE_AS_NEAREST_COMMAND = "execute as @p run"
